INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (1,1,'Moderato',4);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (2,2,'Andante',4);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (3,3,'Moderato',4);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (4,4,'Adagio',4);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (5,5,'Epilog',4);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (6,6,'SmuteËnÌ pochod',4);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (7,7,'Marche funebre',4);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (8,1,'Allegro',10);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (9,2,'Adagio',10);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (10,3,'Allegretto',10);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (11,4,'Andante',10);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (12,1,'Moderato',15);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (13,2,'Piu mosso',15);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (14,3,'Con moto',15);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (15,4,'Allegro',15);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (16,1,'Balada (Tam dole na dole)',18);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (17,2,'SedÏl vÏzeÚ (SedÏl jeden vÏzeÚ)',18);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (18,3,'Balada (Rychtarova KaËenka)',18);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (19,4,'Rodinu m·m',18);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (20,1,'Andante',22);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (21,2,'(bez oznaËenÌ)',22);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (22,3,'Allegro',22);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (23,4,'(bez oznaËenÌ)',22);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (24,1,'Adagio',23);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (25,2,'Adagio',23);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (26,1,'⁄vod',29);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (27,2,'Gospodi pomiluj',29);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (28,3,'Slava',29);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (29,4,'VÏruju',29);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (30,5,'Svet',29);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (31,6,'Blagoslovljen',29);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (32,7,'AgnÏËe boûij',29);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (33,8,'Dohra. SÛlo varhan',29);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (34,1,'Zlat· uliËka',35);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (35,2,'PlaËÌcÌ font·na',35);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (36,3,'Belveder1916',35);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (37,1,'Andante ñ Meno mosso ñ Da capo',37);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (38,2,'Allegro ñ Moderato ñ Allegro',37);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (39,3,'Moderato ñ Con moto ñ Moderato',37);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (40,4,'Allegro',37);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (41,5,'Adagio ñ Presto - Adagio',37);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (42,6,'Scherzo ñ Trio - Tempo I.',37);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (43,7,'Moderato',37);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (44,1,'Neseme,  neseme m·jÌËek',52);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (45,2,'VyletÏl sokkol',52);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (46,3,'M·me kr·lku chromou',52);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (47,4,'Hajsa,  hajsa,  m· kr·lenko, hejsa',52);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (48,5,'Co to ten kr·l za kr·lovnu dostal',52);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (49,6,'Cib, cib,  cibulenka',52);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (50,7,'äohajova mlad· ûena',52);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (51,8,'Pojedem do ml˝na',52);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (52,9,'Naöa kr·lovna',52);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (53,10,'Vrby se n·m zelenajÌ',52);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (54,1,'Ej ûalo dievËa',55);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (55,2,'Ej, bude zima,  bude mr·z',55);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (56,3,'Pansk· l˙Ëka je zelen·',55);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (57,4,'Jede furman dolin˙',55);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (58,5,'N·ö JanyËko malovan˝',55);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (59,6,'KeÔ ja pojdem na tu vojnu,  mil· m·!',55);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (60,7,'Vysoko si,  laötovienka lietala',55);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (61,1,'Starod·vn˝ I.',57);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (62,2,'Poûehnan˝',57);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (63,3,'Dym·k',57);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (64,4,'Starod·vn˝ II',57);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (65,5,'»eladensk˝',57);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (66,6,'Pilky',57);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (67,1,'Kyrie',62);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (68,2,'Credo',62);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (69,3,'Agnus Dei',62);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (70,1,'Andante',63);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (71,2,'Moderato',63);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (72,3,'Allegro',63);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (73,4,'Con moto',63);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (74,1,'Ty hodiny vÌvanskÈ',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (75,2,'Ked si j· zazpÌv·m',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (76,3,'Ach, ty Jurko, Jurenko',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (77,4,'Maryö, moja Maryö',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (78,5,'Uû sa mnÏ m˘j mil˝ pryË ubÌr·',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (79,6,'Plelo dÌvËa, plelo len',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (80,7,'Slubovals mi, ûe mÏ vezmeö',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (81,8,'»Ì to pachole v noci chodÌ',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (82,9,'»Ì je to dÏvËe na tom vröku',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (83,10,'Dyû j· budu leûat v ËernÈm lesi',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (84,11,'BÏûi voda,  bÏûi',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (85,12,'HradËanskÈ hodiny z temna bijou',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (86,13,'Na Ëernej ho¯e sedl·Ëek o¯e',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (87,14,'Na JavorinÏ [recte Javo¯ina]',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (88,15,'V tem hruöeckÈm ËirÈm poli',66);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (89,1,'»eladensk˝',67);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (90,2,'Pilky',67);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (91,1,'Troj·k',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (92,2,'Silnice',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (93,3,'Tetka',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (94,4,'KukaËka',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (95,5,'Trojka',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (96,6,'Starod·vn˝',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (97,7,'Kalamajka',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (98,8,'Siv· holubiËka',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (99,9,'SekereËka',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (100,10,'Roûek',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (101,11,'KonopÏ',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (102,12,'»eladensk˝',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (103,13,'Koûuöek',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (104,14,'KoryËansk˝ troj·k',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (105,15,'Kyjov˝',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (106,16,'Valaöka',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (107,17,'Sedl·ck·',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (108,18,'Do kola',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (109,19,'Troj·k laösk˝',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (110,20,'Poûehnan˝',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (111,21,'Kolo',76);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (112,1,'Ej nebudu ja dobr˝',84);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (113,2,'Ej sedeu sem ja sedeu',84);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (114,3,'Ej öetko æudia vravia',84);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (115,4,'Pod javorkom,  pod zelen˝m',84);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (116,5,'Ide KraËuÚ, ide',84);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (117,6,'Byæa jedna sir· vdova',84);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (118,7,'Na hor·ch,  na doæ·ch',84);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (119,8,'äla mil· na zd·v·nÌ ',84);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (120,1,'Ten ukvalsk˝ kostelÌËek: Starod·vn˝ laösk˝',89);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (121,2,'TovaËov,  TovaËov,  tovaËovskÈ z·mek',89);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (122,3,'Pila¯sk·: Na pile zme do¯ezale',89);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (123,4,'Aj ûeny: VrtÏn·',89);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (124,5,'Krajcpolka: Bratr um¯el  j· sem zust·l',89);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (125,1,'Iöly panny na jahody',90);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (126,2,'V†tom velickÈm poli',90);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (127,3,'ProË kalino,  neprokvÈt·ö?',90);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (128,4,'Putovali hudci',90);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (129,5,'A byl jeden zeman',90);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (130,1,'Con moto',92);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (131,2,'Con moto',92);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (132,3,'Allegro',92);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (133,4,'Adagio',92);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (134,1,'Naöe veËery',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (135,2,'LÌstek odvanut˝',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (136,3,'PojÔte s†n·mi',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (137,4,'Fr˝deck· Panna Maria',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (138,5,'ätÏbetaly jak laötoviËky',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (139,6,'Nelze domluvit!',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (140,7,'Dobrou noc!',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (141,8,'Tak neskonale ˙zko',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (142,9,'V†pl·Ëi',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (143,10,'S˝Ëek neodletÏl',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (144,11,'Andante',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (145,12,'Allegretto',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (146,13,'Piu mosso',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (147,14,'Allegro',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (148,15,'Vivo',96);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (149,1,'Leze krtek podle meze',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (150,2,'Karel do pekla zajel',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (151,3,'Franta ras˘, hr·l na basu',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (152,4,'DÏl·m, dÏl·m k·z·nÌ',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (153,5,'HÛ, hÛ, kr·vy dÛ',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (154,6,'Koza bÌl· hruöky sbÌr·',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (155,7,'Vaöek,  paöek,  bubenÌk',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (156,8,'FrantÌku,  FrantÌku',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (157,9,'⁄vod',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (158,10,'ÿÌpa se vd·vala',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (159,11,'NenÌ lepöÌ jako z†jara',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (160,12,'Leze krtek podle meze',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (161,13,'Karel do pekla zajel',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (162,14,'RoztrhanÈ kalhoty',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (163,15,'Franta ras˘, hr·l na basu',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (164,16,'N·ö pes, n·ö pes',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (165,17,'DÏl·m, dÏl·m k·z·nÌ',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (166,18,'Star· b·ba Ëarovala',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (167,19,'HÛ, hÛ, kr·vy dÛ',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (168,20,'Moje ûena maluËiËk·',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (169,21,'B·ba leze do bezu',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (170,22,'Koza bÌl· hruöky sbÌr·',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (171,23,'NÏmec brouk, hrnce tlouk',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (172,24,'Koza leûÌ na senÏ',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (173,25,'Vaöek,  paöek,  bubenÌk',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (174,26,'FrantÌku,  FrantÌku',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (175,27,'Sedet medviÔ na kolodi ',102);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (176,1,'Andante',107);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (177,2,'Allegretto',107);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (178,3,'Adagio ñ nedokonËeno',107);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (179,1,'Allegro',109);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (180,2,'Andante',109);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (181,3,'Moderato',109);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (182,4,'Allegretto',109);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (183,5,'Allegro',109);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (184,1,'Adagio',111);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (185,2,'Con moto',111);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (186,3,'Con moto',111);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (187,4,'Con moto',111);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (188,1,'Andante',112);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (189,2,'Adagio',112);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (190,3,'Moderato',112);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (191,4,'Allegro',112);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (192,1,'A choù sem ja drobÚuöinka drobna',113);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (193,2,'Dyû sem öel okolo vrat',113);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (194,3,'A choù  sem dÏvucha chudobnÈho otce',113);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (195,4,'To naöe staveni z drobneho kameni',113);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (196,5,'Aj, co to tam öusti',113);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (197,6,'V kolaji voda',113);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (198,7,'Aj, co to je za slaviËek',113);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (199,8,'Panimamo,  övarnu cerku matÏ',113);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (200,9,'A dybystÏ zap¯ihli ötyradvacet koni',113);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (201,10,'V Ëernym lese ptaËek zpiva ',113);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (202,1,'NÏumrem ja na zemi',116);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (203,2,'äiel som cez mÏsto',116);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (204,3,'ätyry kosy',116);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (205,4,'Na Slatinsk˝ch l˙k·ch',116);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (206,5,'äiroko Ôaleko',116);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (207,6,'Uû tÏbe AniËka ',116);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (208,1,'Con moto',117);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (209,2,'Balada. Noc moto',117);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (210,3,'Allegretto',117);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (211,4,'Adagio',117);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (212,1,'P¯edtucha',118);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (213,2,'Smrt',118);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (214,1,'Con moto',121);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (215,2,'Adagio',121);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (216,3,'Allegretto (Po, ûehnan˝)',121);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (217,4,'Con moto  (Allegro ñ Dym·k)   ',121);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (218,1,'Moderato',123);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (219,2,'Adagio',123);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (220,3,'Andante con moto',123);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (221,4,'Presto-Andante-Presto',123);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (222,5,'Adagio',123);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (223,6,'Andante',123);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (224,1,'Smrt AndrijovaÙ',124);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (225,2,'Smrt Ostapova',124);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (226,3,'ProroctvÌ a smrt Tarase Bulby',124);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (227,1,'Andante',125);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (228,2,'Allegro',125);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (229,3,'Con moto',125);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (230,4,'Con moto',125);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (231,5,'Meno mosso',125);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (232,6,'Adagio',125);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (233,7,'Adagio ñ Tempo I.',125);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (234,1,'Ondraö, Ondraö.',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (235,2,'Ty ukva≥sky kosteliËku! (proti tobÏ Ëerny les)',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (236,3,'Ma mi≥a mamulko',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (237,4,'Na tych fojtovych ≥ukach',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (238,5,'ProË kalinko smutna stojiö?',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (239,6,'Fojtova Hanka',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (240,7,'Pasava≥a kravareËka',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (241,8,'Co su to za tinÏ?',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (242,9,'V naöim dvo¯e dub',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (243,10,'Dyû sem ja öe≥ p¯es Ëerny les',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (244,11,'Ty ukva≥sky kosteliËku, hej! (stojiö na pÏknym travniËku) ',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (245,12,'Pan Buh vam zap≥aù',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (246,13,'Dyû sem ja öe≥ ko≥em dvorka ',129);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (247,1,'Ondraö, Ondraö!',130);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (248,2,'Ty ukva≥sky kosteliËku!',130);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (249,3,'Ny tych fojtovych ≥ukach',130);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (250,4,'Ty ukva≥sky kosteliËku, hej!',130);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (251,5,'Pan Buh vam zap≥aù!',130);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (252,6,'Fojtova Hanka',130);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (253,1,'Con moto',135);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (254,2,'Adagio',135);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (255,3,'Con moto',135);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (256,4,'Andante',135);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (257,1,'Andante',140);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (258,2,'Molto adagio',140);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (259,3,'Andantino',140);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (260,4,'Presto',140);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (261,1,'Potkal jsem mladou cig·nku',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (262,2,'Ta Ëern· cig·nka',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (263,3,'SvatojanskÈ muöky tanËija po hr·zi',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (264,4,'Uû mladÈ vlaöt˙vky ve hnÌzdÏ vrnoûÌ',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (265,5,'TÏûko sa mi o¯e, vyspal sem sa malo',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (266,6,'Hajsi,  vy sivÌ volci',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (267,7,'Ztratil sem kolÌËek',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (268,8,'NehleÔte, voleËci',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (269,9,'VÌtaj,  JanÌËku ',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (270,10,'Boûe d·ln˝, nesmrteln˝',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (271,11,'Tahne v˘Úa k†lesu',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (272,12,'Tmav· olöinka',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (273,13,'[pf intermezzo]',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (274,14,'SlnÈËko sa zdvih·',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (275,15,'Moji sivÌ volci',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (276,16,'Co sem to udÏlal?',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (277,17,'Co komu s˙zeno',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (278,18,'Nedb·m j· vËil o nic',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (279,19,'LetÌ straka letÌ',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (280,20,'M·m j· panenku',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (281,21,'M˘j drah˝ tatÌËku',144);
INSERT INTO database_of_janacek_works_piecemovement (piece_movement_id, movement_order, movement_title, piece_id) VALUES (282,22,'S Bohem, rodn˝ kraju ',144);